"""ctatai app models

Revision ID: 85b4ee6bae84
Revises: e187e8db9d0a
Create Date: 2023-04-12 14:33:32.926864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85b4ee6bae84"
down_revision = "e187e8db9d0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
