"""connection model created

Revision ID: a27c286e4870
Revises: e29529664429
Create Date: 2023-04-12 16:02:24.110263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a27c286e4870"
down_revision = "e29529664429"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connection")
    # ### end Alembic commands ###
