"""chapters_quantity field added

Revision ID: e187e8db9d0a
Revises: e5e7d29780bf
Create Date: 2023-04-11 16:48:40.292564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e187e8db9d0a"
down_revision = "e5e7d29780bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("manga", sa.Column("chapters_quantity", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manga", "chapters_quantity")
    # ### end Alembic commands ###
