"""ctatai app models

Revision ID: e29529664429
Revises: 85b4ee6bae84
Create Date: 2023-04-12 15:01:16.534615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e29529664429"
down_revision = "85b4ee6bae84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promt")
    # ### end Alembic commands ###
