"""Type field added

Revision ID: e5e7d29780bf
Revises: f5279b125267
Create Date: 2023-04-11 16:47:30.423629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e5e7d29780bf"
down_revision = "f5279b125267"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("manga", sa.Column("type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manga", "type")
    # ### end Alembic commands ###
