"""connection model updated

Revision ID: ed8402afc2de
Revises: a27c286e4870
Create Date: 2023-04-12 16:08:12.450989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed8402afc2de"
down_revision = "a27c286e4870"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connection", sa.Column("code", sa.String(), nullable=False))
    op.add_column("connection", sa.Column("ws_code", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connection", "ws_code")
    op.drop_column("connection", "code")
    # ### end Alembic commands ###
